### ISSUE TITLE
lintrunner check doesn't fail if command is obviously wrong

### ISSUE THREAD

**Issue by ezyang** [suo/lintrunner#3] opened 2022-04-18 17:35 UTC
with

```
[[linter]]
code = 'BARF'
include_patterns = [
    'tools/codegen/**/*.py'
]
command = [
    'python3',
    'missing_file.py',
    '--',
    '@{{PATHSFILE}}'
]
```

when I run

```
(base) ezyang-mbp:pytorch ezyang$ lintrunner --take BARF
ok No lint issues.
```

which is obviously wrong since the command totally failed

**Comment by suo** [comment] 2022-05-02 23:35
This will fail if the linter actually gets executed (e.g. we detect a file change that matches the include pattern). Otherwise, by design we never invoke the linter command.

Probably a wontfix?

**Closed by suo** 2022-05-02 23:35 UTC
